name: Publish to NuGet

on:
  push:
    branches: [ main ]
    tags:     [ "v*" ]
  workflow_dispatch: {}

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x

      - name: Get csproj Version
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" src/Shardo.PcPos.Sadad/Shardo.PcPos.Sadad.csproj)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get NuGet Latest Version
        id: get_nuget_version
        run: |
          PACKAGE_ID="shardo.pcpos.sadad"
          URL="https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID,,}/index.json"
          NUGET_VERSION=$(curl -s $URL | jq -r '.versions[-1]' || echo "")
          echo "nuget_version=$NUGET_VERSION" >> $GITHUB_OUTPUT

      - name: Compare Versions
        id: compare
        run: |
          if [ -z "${{ steps.get_nuget_version.outputs.nuget_version }}" ]; then
            echo "same=false" >> $GITHUB_OUTPUT
          elif [ "${{ steps.get_version.outputs.version }}" = "${{ steps.get_nuget_version.outputs.nuget_version }}" ]; then
            echo "same=true" >> $GITHUB_OUTPUT
          else
            echo "same=false" >> $GITHUB_OUTPUT
          fi

      - name: Restore
        if: steps.compare.outputs.same == 'false'
        run: dotnet restore

      - name: Build
        if: steps.compare.outputs.same == 'false'
        run: dotnet build --configuration Release --no-restore

      - name: Pack (use Version from csproj)
        if: steps.compare.outputs.same == 'false'
        run: |
          dotnet pack src/Shardo.PcPos.Sadad/Shardo.PcPos.Sadad.csproj \
            --configuration Release \
            -p:ContinuousIntegrationBuild=true \
            -o out

      - name: Publish to nuget.org (nupkg & snupkg)
        if: steps.compare.outputs.same == 'false'
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "out/*.nupkg"  --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push "out/*.snupkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
